name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # "main" ブランチに push したときにデプロイ

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        env: # ビルド時に環境変数を注入
         NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
         PORT:  ${{ secrets.PORT }}
        run: npm install

      - name: Build Next.js project
        env:
         NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
         PORT: ${{ secrets.PORT }}
        run: npm run build

      - name: Prepare deploy folder
        run: |
          mkdir deploy
          cp -r .next/standalone/. deploy/
